apiVersion: bkauf.com/v1
kind: cluster
metadata:
  name: a-team-1
  labels:
    cluster-owner: bkauf
spec:
  compositionRef:
    # Possible values cluster-gcp, cluster-azure, cluster-aws
    name: cluster-aws
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    version: "1.21"
    #minNodeCount: 2
  writeConnectionSecretToRef:
    namespace: a-team
    name: cluster
