apiVersion: demo.anthos.com/v1
kind: Cluster
metadata:
  name: vikas-cluster
  labels:
    cluster-owner: bkauf
spec:
  compositionRef:
    # Possible values cluster-gcp, cluster-azure, cluster-aws
    name: cluster-gcp
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    k8sVersion: "1.24"
    fleetProject: "261832825633"
    minNodeCount: 3
    adminUsers:
    - bkauf@google.com  
