apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: test-cluster
  namespace: team-a
  labels:
    cluster-owner: prod-cluster-2
spec:
  compositionRef:
    # Possible values cluster-gcp, cluster-azure, cluster-aws
    name: cluster-gcp
  parameters:
    # Possible values small, medium, large
    nodeSize: medium
    k8sVersion: "1.24"
    fleetProject: "261832825633"
    minNodeCount: 3
    adminUsers:
    - bkauf@google.com  
  #writeConnectionSecretToRef:
  #  namespace: default
  #  name: b-team
