apiVersion: container.gcp.gke.cloud.google.com/v1beta1
kind: Cluster
metadata:
  name: cluster-1 # edit to match cluster name
  annotations:
    crossplane.io/external-name: cluster-1 # edit to match cluster name
spec:
  #managementPolicy: ObserveOnly # used to gather all resource fields
  providerConfigRef: 
    name: default-gcp # edit to match GCP providerconfig
  forProvider:
    location: us-central1-c # edit to match location
