apiVersion: demo.anthos.com/v1
kind: NodePool
metadata:
  name: test-nodepool
  labels:
    cluster-owner: bkauf
spec:
  compositionRef:
    # Possible values gcp-node-pool, gcp-gke-nodepool-up
    name: gcp-gke-nodepool-up
  parameters:
    clusterName: "alan-cluster-jcxr8-74vm5"
    # Possible values small, medium, large
    nodeSize: medium
    minNodeCount: 1
